<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<form action="index.php" method="post">
	<fieldset>
		<input type="hidden" name="page" value="structure" />
		<input type="hidden" name="category_id" value="<?php echo $categoryId ?>" />
		<input type="hidden" name="clang" value="<?php echo $clangId ?>" />
		<input type="hidden" name="func" value="<?php echo $action ?>" />
	</fieldset>

	<?php
	$add_url = '';
	if ($canAdd) {
		$add_url = 'index.php?page=structure&category_id='.$categoryId.'&clang='.$clangId.'&func=addArticle';
	}
	$add_article = sly_Util_HTML::getSpriteLink($add_url, t('add_article'), 'article-add');

	$table = new sly_Table('sly-structure-articles');
	$table->addColumn(new sly_Table_Column($add_article, '', '', array('class' => 'sly-col-icon sly-icon')));
	$table->addColumn(new sly_Table_Column(t('article_name'), '', '', array('class' => 'sly-col-name')));
	$table->addColumn(new sly_Table_Column(t('articletype'), '', '', array('class' => 'sly-col-arttype')));

	$isActive = $renderAddArticle || $renderEditArticle;

	if ($isActive) {
		$table->addClass('sly-active');
		$table->addColumn(new sly_Table_Column(t('position_short'), '', '', array('class' => 'sly-col-pos')));
	}

	$table->addColumn(new sly_Table_Column(t('status'), '', '', array('class' => 'sly-col-status')));
	$table->openBuffer();

	if ($renderAddArticle) {
		$this->render(
			sly_Controller_Structure::$viewPath.'article_table_row_add.phtml',
			array('maxPosition' => $maxPosition),
			false
		);
	}

	foreach ($articles as $article) {
		if ($renderEditArticle && $renderEditArticle == $article->getId()) {
			$this->render(
				sly_Controller_Structure::$viewPath.'article_table_row_edit.phtml',
				array('article' => $article, 'maxPosition' => $maxPosition),
				false
			);
		}
		else {
			$this->render(
				sly_Controller_Structure::$viewPath.'article_table_row.phtml',
				array(
					'article' => $article, 'statusTypes' => $statusTypes,
					'canEdit' => $canEdit, 'isActive' => $isActive
				),
				false
			);
		}
	}

	if (!$renderAddArticle && empty($articles)) {
		?>
		<tr>
			<td colspan="<?php echo $isActive ? 5 : 4 ?>" class="sly-col-empty center"><?php echo t('no_articles_yet') ?></td>
		</tr>
		<?php
	}

	$table->closeBuffer();
	print $table->render();
	?>
</form>
