<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<form action="index.php" method="post">
	<fieldset>
		<input type="hidden" name="page" value="structure" />
		<input type="hidden" name="category_id" value="<?php echo $categoryId ?>" />
		<input type="hidden" name="clang" value="<?php echo $clangId ?>" />
		<input type="hidden" name="func" value="<?php echo $action ?>" />
	</fieldset>

	<?php
	$add_url = '';
	if ($canAdd) {
		$add_url = 'index.php?page=structure&category_id='.$categoryId.'&clang='.$clangId.'&func=addCategory';
	}
	$add_category = sly_Util_HTML::getSpriteLink($add_url, t('add_category'), 'category-add');

	$table = new sly_Table('sly-structure-categories');
	$table->addColumn(new sly_Table_Column($add_category, '', '', array('class' => 'sly-col-icon sly-icon')));
	$table->addColumn(new sly_Table_Column(t('category'), '', '', array('class' => 'sly-col-name')));

	$isActive = $renderAddCategory || $renderEditCategory;

	if ($isActive) {
		$table->addClass('sly-active');
		$table->addColumn(new sly_Table_Column(t('position_short'), '', '', array('class' => 'sly-col-pos')));
	}

	$table->addColumn(new sly_Table_Column(t('status'), '', '', array('class' => 'sly-col-status')));
	$table->openBuffer();

	if ($categoryId != 0 && $currentCategory) {
		?>
		<tr>
			<td class="sly-col-icon sly-icon">&nbsp;</td>
			<td class="sly-col-name"><a href="index.php?page=structure&amp;category_id=<?php echo $currentCategory->getParentId().'&amp;clang='.$clangId ?>">..</a></td>
			<?php if ($isActive): ?><td class="sly-col-pos">&nbsp;</td><?php endif ?>
			<td class="sly-col-status">&nbsp;</td>
		</tr>
		<?php
	}

	if ($renderAddCategory) {
		$this->render(
			sly_Controller_Structure::$viewPath.'category_table_row_add.phtml',
			array('maxCatPosition' => $maxCatPosition),
			false
		);
	}

	foreach ($categories as $category) {
		if ($renderEditCategory && $renderEditCategory == $category->getId()) {
			$this->render(
				sly_Controller_Structure::$viewPath.'category_table_row_edit.phtml',
				array('category' => $category, 'maxCatPosition' => $maxCatPosition),
				false
			);
		}
		else {
			$this->render(
				sly_Controller_Structure::$viewPath.'category_table_row.phtml',
				array('category' => $category, 'statusTypes' => $statusTypes, 'isActive' => $isActive),
				false
			);
		}
	}

	if (!$renderAddCategory && !$currentCategory && empty($categories)) {
		?>
		<tr>
			<td colspan="<?php echo $isActive ? 5 : 4 ?>" class="sly-col-empty center"><?php echo t('no_categories_yet') ?></td>
		</tr>
		<?php
	}

	$table->closeBuffer();
	print $table->render();
	?>
</form>

