<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

////////////////////////////////////////////////////////
// print breadcrumb path

$base    = 'index.php?page=mediapool_structure&amp;cat_id=';
$path    = '<li> : <a href="'.$base.'0">'.ht('start').'</a></li>';
$isForm  = $action === 'add' || $action === 'edit';
$addMode = $action === 'add';
$catID   = $cat    ? $cat->getId()    : 0;
$editID  = $active ? $active->getId() : 0;

if ($cat) {
	$parents = $cat->getParentTree();

	foreach ($parents as $parent) {
		$path .= '<li> : <a href="'.$base.$parent->getId().'">'.sly_html($parent->getName()).'</a></li>';
	}

	$path .= '<li> : <a href="'.$base.$catID.'">'.sly_html($cat->getName()).'</a></li>';
}

?>
<div class="sly-navi-path">
	<ul>
		<li><?php echo t('path') ?></li>
		<?php echo $path ?>
	</ul>
</div>
<?php

print sly_Helper_Message::renderFlashMessage();

////////////////////////////////////////////////////////
// start form if needed

if ($isForm) {
	?>
	<form action="index.php" method="post">
		<fieldset>
			<input type="hidden" name="page" value="mediapool_structure" />
			<input type="hidden" name="cat_id" value="<?php echo $catID ?>" />
			<input type="hidden" name="func" value="<?php echo $action ?>" />
			<?php	if ($active): ?>
			<input type="hidden" name="edit_id" value="<?php echo $active->getId() ?>" />
			<?php endif ?>
			<?php print sly_Util_Csrf::renderInputTag() ?>
			<?php foreach ($args as $name => $value): ?>
			<input type="hidden" name="args[<?php echo $name ?>]" value="<?php echo sly_html($value) ?>" />
			<?php endforeach ?>
		</fieldset>
		<?php
}

$rawBase = 'index.php?page=mediapool_structure&cat_id=';
$table   = new sly_Table('sly-mediapool-structure');

$table->addColumn(sly_Table_Column::sprite('mediacat-add', $rawBase.$catID.'&func=add', t('add_category'), 'sly-col-icon'));
$table->addColumn(sly_Table_Column::factory(t('category_name'), 'sly-col-name'));
$table->addColumn(sly_Table_Column::factory(t('function'), 'sly-col-func'));

$table->setIsEmpty(empty($children) && $action !== 'add');
$table->setEmptyNotice(t('no_categories_yet'));
$table->openBuffer();

if ($addMode) {
	?>
	<tr class="sly-active">
		<td class="sly-col-icon sly-icon"><?php echo sly_Util_HTML::getSpriteLink('', t('add_category'), 'mediacat') ?></td>
		<td class="sly-col-name sly-has-input"><div><input class="sly-form-text" type="text" size="10" id="sly-form-field-name" name="catname" value="" autofocus="autofocus" required="required" placeholder="<?php echo ht('category_name') ?>" /></div></td>
		<td class="sly-col-func sly-has-input"><div><input type="submit" class="sly-form-submit" value="<?php echo t('add') ?>" /></div></td>
	</tr>
	<?php
}

foreach ($children as $cat) {
	$id = $cat->getId();

	if ($action === 'edit' && $editID === $id) {
		?>
		<tr class="sly-active">
			<td class="sly-col-icon sly-icon"><?php echo sly_Util_HTML::getSpriteLink('', $cat->getName(), 'mediacat') ?></td>
			<td class="sly-col-name sly-has-input"><div><input class="sly-form-text" type="text" id="sly-form-field-name" name="catname" value="<?php echo sly_html($cat->getName()) ?>" autofocus="autofocus" required="required" placeholder="<?php echo ht('category_name') ?>" /></div></td>
			<td class="sly-col-func sly-has-input" colspan="2"><div><input type="submit" class="sly-form-submit" value="<?php echo t('save') ?>" /></div></td>
		</tr>
		<?php
	}
	else {
		?>
		<tr>
			<td class="sly-col-icon sly-icon"><?php echo sly_Util_HTML::getSpriteLink($rawBase.$catID.'&func=edit&edit_id='.$id, $cat->getName(), 'mediacat') ?></td>
			<td class="sly-col-name"><a href="<?php echo $base.$id ?>"><?php echo sly_html($cat->getName()) ?></a></td>
			<td class="sly-col-func">
				<a href="<?php echo $base.$catID ?>&amp;func=edit&amp;edit_id=<?php echo $id ?>"><?php echo t('change')?></a>
				<a href="<?php echo $base.$catID ?>&amp;func=delete&amp;edit_id=<?php echo $id ?>" class="sly-action sly-delete sly-postlink"><?php echo t('delete') ?></a>
			</td>
		</tr>
		<?php
	}
}

$table->closeBuffer();
print $table->render();

if ($isForm) {
	print '</form>';
}
