authorisation:
  pages:
    title: 'translate:pages'
    token:
      structure: 'translate:structure'
      addons: 'translate:addons'
      user: 'translate:users'
      mediapool: 'translate:mediapool'
  article:
    title: 'translate:articles'
    token:
      edit: 'translate:edit'
      move: 'translate:move'
      publish: 'translate:publish'
      edittype: 'translate:change_articletype'
      editcontent: 'translate:edit_contents'
    supers:
      editcontent: ['edit']
      edittype: ['edit']
  module:
    title: 'translate:modules'
    list: 'sly_Authorisation_ModuleListProvider'
    token:
      add: 'translate:add'
      edit: 'translate:edit'
      delete: 'translate:delete'
      move: 'translate:move'
    supers:
      add: ['edit','delete']
      edit: ['delete', 'move']
  language:
    title: 'translate:languages'
    list: 'sly_Authorisation_LanguageListProvider'
    token:
      access: 'translate:grant_access'
  mediacategory:
    title: 'translate:media_categories'
    list: 'sly_Authorisation_MediaCategoryListProvider'
    token:
      access: 'translate:grant_access'
  user:
    title: 'translate:users'
    token:
      add: 'translate:add'
      edit: 'translate:edit'
      delete: 'translate:delete'

rest:
  # shortcut definitions to save a lot of typing and typos
  controller_routes:
    sly_Controller_Rest_Articles:
      base: '/v1/articles'
      identifier: ':id-:clang'
      verbs: [index, get, create, update, delete]

  routes:
    login:
      pattern: 'POST /v1/login'
      controller: sly_Controller_Rest_Login
      action: login
    logout:
      pattern: 'POST /v1/logout'
      controller: sly_Controller_Rest_Login
      action: logout
