<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<div class="sly-area sly-credits">
	<h2>SallyCMS <?php echo sly_Core::getVersion() ?></h2>

	<div class="sly-area-content">
		<p><?php echo t('credits_text') ?></p>
		<p><?php echo t('credits_thankyou') ?></p>
	</div>
</div>

<table class="sly-table sly-addonlist" summary="<?php echo t('credits_caption') ?>">
	<caption><?php echo t('credits_caption') ?></caption>
	<thead><tr>
		<th class="sly-col-icon sly-icon">&nbsp;</th>
		<th class="sly-col-name"><?php echo t('addon') ?></th>
		<th class="sly-col-version"><?php echo t('version') ?></th>
		<th class="sly-col-author"><?php echo t('author') ?></th>
	</tr></thead>
	<tbody>

	<?php

	$service = sly_Service_Factory::getComponentService();

	foreach ($service->getRegisteredComponents() as $addon) {
		$params['type']        = 'addon';
		$params['name']        = $addon;
		$params['version']     = $service->getVersion($addon);
		$params['supportPage'] = sly_Helper_Component::getSupportPage($addon);

		print $this->render('credits/row.phtml', $params);

		if ($service->isAvailable($addon)) {
			$params['type'] = 'plugin';

			foreach ($service->getRegisteredComponents($addon) as $plugin) {
				list($addon, $pluginName) = explode('/', $plugin);

				$params['type']        = 'plugin';
				$params['name']        = $pluginName;
				$params['addon']       = $addon;
				$params['version']     = $service->getVersion($plugin);
				$params['supportPage'] = sly_Helper_Component::getSupportPage($plugin);

				print $this->render('credits/row.phtml', $params);
			}
		}
	}

	if (count($service->getRegisteredComponents()) === 0) {
		?>
		<tr>
			<td class="sly-col-empty center" colspan="5"><?php echo t('no_addons_found') ?></td>
		</tr>
		<?php
	}

	?>
	</tbody>
</table>
