<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<div class="sly-area sly-credits">
	<h2>SallyCMS <?php echo sly_Core::getVersion() ?></h2>

	<div class="sly-area-content">
		<p><?php echo t('credits_text') ?></p>
		<p><?php echo t('credits_thankyou') ?></p>
	</div>
</div>

<table class="sly-table sly-pkglist" summary="<?php echo t('credits_caption') ?>">
	<caption><?php echo t('credits_caption') ?></caption>
	<thead><tr>
		<th class="sly-col-icon sly-icon">&nbsp;</th>
		<th class="sly-col-name" colspan="2"><?php echo t('addon') ?></th>
		<th class="sly-col-version"><?php echo t('version') ?></th>
		<th class="sly-col-author"><?php echo t('author') ?></th>
	</tr></thead>
	<tbody>

	<?php

	$service  = sly_Service_Factory::getAddOnService();
	$pservice = $service->getPackageService();
	$addons   = $service->getRegisteredAddOns();
	$skip     = array();
	$link     = true;

	foreach ($addons as $addon) {
		if (in_array($addon, $skip)) continue;

		$params['link']        = $link;
		$params['type']        = 'addon';
		$params['name']        = $addon;
		$params['version']     = $service->getVersion($addon);
		$params['supportPage'] = sly_Helper_Package::getSupportPage($addon);

		$this->render('credits/row.phtml', $params, false);

		$children = $pservice->getChildren($addon);

		foreach ($children as $child) {
			$params['type']        = 'addon-child';
			$params['name']        = $child;
			$params['version']     = $service->getVersion($child);
			$params['supportPage'] = sly_Helper_Package::getSupportPage($child);

			$this->render('credits/row.phtml', $params, false);

			$skip[] = $child;
		}
	}

	if (count($addons) === 0) {
		?>
		<tr>
			<td class="sly-col-empty center" colspan="5"><?php echo t('no_addons_found') ?></td>
		</tr>
		<?php
	}

	?>
	</tbody>
</table>

<table class="sly-table sly-pkglist" summary="<?php echo t('credits_caption') ?>">
	<caption><?php echo t('credits_caption') ?></caption>
	<thead><tr>
		<th class="sly-col-icon sly-icon">&nbsp;</th>
		<th class="sly-col-name" colspan="2"><?php echo t('package') ?></th>
		<th class="sly-col-version"><?php echo t('version') ?></th>
		<th class="sly-col-author"><?php echo t('author') ?></th>
	</tr></thead>
	<tbody>

	<?php

	$service  = sly_Service_Factory::getVendorPackageService();
	$packages = $service->getPackages();
	$link     = false;

	foreach ($packages as $package) {
		$params['link']        = $link;
		$params['type']        = 'addon';
		$params['name']        = $package;
		$params['version']     = $service->getVersion($package);
		$params['supportPage'] = sly_Helper_Package::getSupportPage($package);

		$this->render('credits/row.phtml', $params, false);
	}

	?>
	</tbody>
</table>
