<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$service     = sly_Service_Factory::getPackageService();
$helpfile    = $service->baseDirectory($package).'/help.php';
$version     = $service->getVersion($package);
$author      = $service->getAuthor($package);
$supportPage = sly_Helper_Package::getSupportPage($package);
$name        = str_replace('/', ' / ', $package);
$format      = '<dt>%s:</dt><dd>%s</dd>';
$credits     = sprintf($format, t('name'), sly_html($name));

if ($version)     $credits .= sprintf($format, t('version'), sly_html($version));
if ($supportPage) $credits .= sprintf($format, t('author'), $supportPage);
elseif ($author)  $credits .= sprintf($format, t('author'), sly_html($author));

?>
<div class="sly-area sly-addon-help">
	<h2><?php echo t('package_help', $name) ?></h2>

	<div class="sly-area-content">
		<?php if (!is_file($helpfile)): ?>
		<p><?php echo t('package_help_file_not_found') ?></p>
		<?php else: ?>
		<?php include $helpfile ?>
		<?php endif ?>
		<dl><?php echo $credits ?></dl>
	</div>

	<div class="sly-area-footer">
		<p><a href="#" onclick="history.go(-1); return false"><?php echo t('back') ?></a></p>
	</div>
</div>
