<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

if (!empty($info))    print sly_Helper_Message::info($info);
if (!empty($warning)) print sly_Helper_Message::warn($warning);

$sublist = dirname(__FILE__).'/sublist.phtml';

if (empty($tree)) {
	print sly_Helper_Message::info(t('no_addons_found'));
}
else {
	?>
	<ul class="sly-addonlist">
		<?php
		foreach ($tree as $addon => $aInfo) {
			$base    = 'index.php?page=addon&amp;component='.urlencode($addon).'&amp;func=';
			$info    = $aInfo;
			$key     = $addon;
			$name    = $addon;
			$classes = $stati[$key]['classes'];

			?>
			<li class="<?php echo $classes ?> component" data-key="<?php echo $key ?>">
				<ul class="details">
					<?php include $sublist; ?>
				</ul>
				<?php
				if (!empty($aInfo['components'])) print '<ul class="plugins">';

				foreach ($aInfo['components'] as $plugin => $pInfo) {
					$key     = $pInfo['key'];
					$base    = 'index.php?page=addon&amp;component='.urlencode($key).'&amp;func=';
					$info    = $pInfo;
					$name    = $plugin;
					$classes = $stati[$key]['classes'];

					?>
					<li class="<?php echo $classes ?> component" data-key="<?php echo $key ?>">
						<ul class="details">
							<?php include $sublist; ?>
						</ul>
					</li>
					<?php
				}

				if (!empty($aInfo['components'])) print '</ul>';
				?>
			</li>
			<?php
		}

		?>
		<li class="error"><?php echo sly_Helper_Message::warn('dummy') ?></li>
	</ul>
	<?php
}
