<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$sidebar = sly_Util_User::getCurrentUser() && $this->hasNavigation();

?>
<div id="sly-topbar"></div>
<div id="sly-page">
	<?php
	print $this->renderView('head.phtml');

	if ($sidebar) {
		print $this->renderView('sidebar.phtml');
	}
	?>
	<div id="content">
